# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a88bfacae2fc1e33c0691823333f57e85f8a3d3ae0bf78b76f86a8ff1a2a737223559aefa870389042e2d7b5da4e300c9c15b41ff53ccebc4189c151de81d034
  sendy_host: http://www.moneyrate360.com/sendy/
test:
  secret_key_base: 917fd09c1317e82542214032c4fbf79c35081bb4ca236ed1d9db33009d7092da29b496a9134b816742c27ebde7837c23da27985aeb1f80aa6bba91eef3a7b7db
  sendy_host: http://www.moneyrate360.com/sendy/
# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: 92c872803b1cca4e5751c9354ecb3bfb7541dd8037ab4ceef964c5702906e9c763ca70506e1c9fed9dc98f0ba515ee2578abae59ff4c6e0fa383a47ff4f40273
  sendy_host: http://www.moneyrate360.com/sendy/
